steps:
  # 0.
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

 # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/review-movie:${SHORT_SHA}", "."]
    dir: "backend"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/review-movie:${SHORT_SHA}"]
    
  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy", 
        "review-movie",
        "--image",
        "gcr.io/$PROJECT_ID/review-movie:${SHORT_SHA}",
        "--timeout",
        "1000s",
        "--port",
        "5010",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY